"""FastAPI application entrypoint for the MarketRadar REST API.

Run locally:
    uvicorn src.api.app:app --reload

Interactive OpenAPI docs are auto-generated by FastAPI from this app's
metadata plus every response_model / Field(description=...) in
src/api/models.py and src/api/routes.py - available at /docs (Swagger
UI) and /redoc once the server is running; the raw schema is at
/openapi.json.

This module owns process-wide concerns only (app metadata, OpenAPI
config, CORS, the top-level exception handler, router registration) -
every actual endpoint lives in src/api/routes.py, and every actual
analysis decision lives in src/pipeline/pipeline.py. See routes.py's
module docstring for the independence rule this whole package follows.

CORS (Task 11): added when building the dashboard (src/api/ was built
in Task 10 with no browser-based consumer yet, and had no CORS
configuration at all - confirmed by testing a real cross-origin OPTIONS
preflight against a running server, which came back 405 with no
Access-Control-Allow-* headers). Without it, every fetch() call from
the dashboard's own origin (localhost:3000 in dev) is blocked by the
browser before it ever reaches this API, regardless of how the
frontend is written - not a style gap but a hard functional blocker
for the exact consumer this task exists to build, so it qualifies as
the "true backend bug" this task's instructions allow fixing. Scoped to
localhost/127.0.0.1 (any port, via regex, since `next dev` picks
whatever port is free) rather than a wildcard - this is a personal,
local-only tool, not a public deployment.

Production origin (deployment: Render backend + Vercel dashboard):
confirmed via a live OPTIONS preflight against the deployed backend
that the Vercel dashboard's origin was being rejected ("Disallowed
CORS origin") because only the localhost regex above matched -
reachable in a browser (unlike curl/docs, which aren't subject to
CORS at all). Added as an explicit exact-string entry in allow_origins,
not folded into the regex or widened to a wildcard, so only this one
known production origin is trusted; allow_origin_regex keeps handling
the arbitrary-port localhost case for local dev.
"""

from __future__ import annotations

import logging

from fastapi import FastAPI, Request
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import JSONResponse

from src.api.routes import router

# Logging (previously missing entirely here - found live: running via
# `uvicorn src.api.app:app`, every logger.info() call anywhere in the
# app, including Pipeline.run()'s own fetch/extract/cluster progress
# logs, was silently invisible. Python's root logger has no handler by
# default; uvicorn only configures handlers for its own "uvicorn"/
# "uvicorn.access"/"uvicorn.error" loggers, not the root logger or this
# project's "src.*" tree, so anything below WARNING fell through to
# logging.lastResort (which only prints WARNING+) with no INFO output
# at all. Same fix src/pipeline/runner.py's own _configure_logging()
# already applies for the CLI (see that function's docstring for the
# same google-genai-log-pollution reasoning) - root stays at WARNING so
# third-party libraries stay quiet, "src" is raised to INFO so this
# project's own log lines (the ones an operator actually wants to see
# in Render's log viewer) show up. No --verbose equivalent here (no CLI
# args in an ASGI process) - always INFO, matching runner.py's default.
logging.basicConfig(level=logging.WARNING, format="%(asctime)s %(levelname)-7s %(name)s: %(message)s", force=True)
logging.getLogger("src").setLevel(logging.INFO)

app = FastAPI(
    title="MarketRadar API",
    description=(
        "REST API over the MarketRadar pipeline (Fetch -> Analyze -> Cluster -> "
        "Verify -> Report). Every endpoint calls src.pipeline.pipeline.Pipeline - "
        "no analysis, fetching, or report-generation logic lives in this package. "
        "See README.md for setup and example requests."
    ),
    version="1.0.0",
)

app.add_middleware(
    CORSMiddleware,
    allow_origins=["https://market-rader.vercel.app"],
    allow_origin_regex=r"https?://(localhost|127\.0\.0\.1)(:\d+)?",
    allow_credentials=False,
    allow_methods=["*"],
    allow_headers=["*"],
)

app.include_router(router)

logger = logging.getLogger(__name__)


@app.exception_handler(Exception)
async def _unhandled_exception_handler(request: Request, exc: Exception) -> JSONResponse:
    """Last-resort safety net: an unhandled exception must never leak a
    raw traceback to an API caller. Pipeline.run() already catches
    everything internally (see pipeline.py's own top-level
    `except Exception`) and returns a structured failure summary
    instead of raising, so reaching this handler indicates a bug in the
    API layer itself, not a pipeline failure - logged at ERROR with the
    real exception for diagnosis, but the client only ever sees a
    generic message, never internal details.
    """
    logger.exception("Unhandled API error on %s %s", request.method, request.url.path)
    return JSONResponse(status_code=500, content={"detail": "Internal server error."})
